#!/bin/bash
echo "Linux Find & Replace Using SED 1.0"
echo "Enter filename: "
read filetowork
echo "Enter string your want to search for: "
read search
echo "Enter string you want to replace it with: "
read replace
echo $search
echo $replace
echo $filetowork
echo "Finding and replacing..."
sed -i s,${search},${replace},g $filetowork