#!/bin/bash
echo "Linux Find & Replace Using SED 1.0"
echo "Enter filename: "
read filetowork
echo "Enter string your want to search for: "
read search
echo "Enter string you want to replace it with: "
read replace
echo "Working in file $filetowork to replace $search with $replace "
echo "Finding and replacing..."
sed -i s,${search},${replace},g $filetowork